### ISSUE TITLE
Gdzie są moje klapki kubota?

### ISSUE THREAD

**Issue by pguz** [pguz/PriAct#1]
Olx http://olx.pl/oferta/avon-czarna-kredka-do-oczu-czaruj-kolorem-nowa-w-kartoniku-CID87-IDansJb.html  Avon czarna kredka do oczu czaruj kolorem nowa w kartoniku  8.0
Olx http://olx.pl/oferta/historia-kosciola-piec-tomow-CID751-IDansIP.html   Historia Kościoła. Pięć tomów  35.0
Olx http://olx.pl/oferta/buciki-chlopiece-h-m-rozm-18-19-stan-idealny-CID88-IDa7Spl.html    Buciki chłopięce H&M rozm. 18-19 stan idealny 40.0
Olx http://olx.pl/oferta/trabant-601-pradnica-6-v-CID5-IDansth.html Trabant 601 prądnica 6 V   40.0
Olx http://olx.pl/oferta/asus-ux300-blue-ray-nowa-mysz-komputerowa-CID99-ID95IVj.html   ASUS UX300 Blue-ray - nowa mysz komputerowa 45.0
Olx http://olx.pl/oferta/dywan-wykladzina-golf-iv-CID5-ID8visp.html Dywan, wykładzina golf IV  50.0
Olx http://olx.pl/oferta/bolerko-slubne-xs-CID87-ID78JDB.html   bolerko ślubne xs  55.0
Olx http://olx.pl/oferta/frezarka-narzedziowa-676p-r-b-1982-stan-techniczny-maszyna-na-chodzie-CID619-IDansqB.html  Frezarka narzędziowa 676P r.b 1982 stan techniczny maszyna na chodzie  12000.0

**Comment by sopello** [comment]
Ustawiłeś na stałe endPage na 10 :)
val endPage = getMaxPageResult(getSourceCode(product, 1))
